import type { NextPage } from 'next'
import Head from 'next/head'
import Navigation from "../components/Navigation"

const Home: NextPage = () => {
  return (
    <main className='h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
    </main>
  )
}

export default Home
